### PR TITLE
Skipped update firmware file not found  | Missed Raising error

### PR DESCRIPTION
**Pull request by asinghx**
Firmware file not found error was missed due to an indentation typo.

### CODE REVIEW

**Comment by asinghx** [comment]
Also added code to only include R2 in latest version if it is not already in `latest_version`. This was done to resolve error in firmware update from 1.3.0 to 1.3.2

**Comment by fabian-n-gude-systems** [comment]
Introduced changes on basis to your pull request.

**Comment by fabian-n-gude-systems** [comment]
Trying partial merge.

**Comment by fabian-n-gude-systems** [comment]
Thank you very much for your contribution!

**Pull request merged**
